name: Run TestRigor Test

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        env:
          API_TOKEN: ${{ secrets.TESTRIGOR_API_TOKEN }}
        run: |
          echo "Suite ID: ${{ secrets.TESTRIGOR_SUITE_ID }}"
          echo "API Token starts with: ${API_TOKEN:0:4}..."

      - name: Trigger TestRigor Test
        run: |
          echo "Triggering TestRigor..."
          set -e # Fail on any error
          RESPONSE=$(curl -s -w "\nHTTP_STATUS_CODE:%{http_code}\n" -X POST "https://app.testrigor.com/api/v1/tests/run" \
            -H "Authorization: Token ${{ secrets.TESTRIGOR_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data "{\"test_suite_id\":\"${{ secrets.TESTRIGOR_SUITE_ID }}\",\"test_case_name\":[\"Demo_WebShop\"]}"
          echo "$RESPONSE"
