name: Run TestRigor Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-demo-webshop-test:
    runs-on: ubuntu-latest

    steps:
      - name: Call TestRigor API
        run: |
          curl -X POST "https://app.testrigor.com/api/v1/tests/run" \
          -H "Authorization: Bearer ${{ secrets.TESTRIGOR_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "test_suite_id": "${{ secrets.TESTRIGOR_SUITE_ID }}",
              }'
